apiVersion: v2
name: flask-app
description: A Helm chart for deploying a Flask application with a PostgreSQL database
version: 0.1.0
appVersion: 1.0.0
dependencies:
  - name: postgresql
    version: "13.2.24"
    repository: "https://charts.bitnami.com/bitnami"
