apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "flask-app.fullname" . }}
  labels:
    {{- include "flask-app.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "flask-app.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "flask-app.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          env:
            - name: DATABASE_USERNAME
              value: {{ .Values.postgresql.auth.username }}
            - name: DATABASE_PASSWORD
              value: {{ .Values.postgresql.auth.password }}
            - name: DATABASE_NAME
              value: {{ .Values.postgresql.auth.database }}
            - name: DATABASE_HOST
              value: flask-app-postgresql
            - name: DATABASE_PORT
              value: "5432"
